# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - make html
    - mv build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
